### PR TITLE
selenium tests optional

### PR DESCRIPTION
**Pull request by peterbe**
What do you think? This way, the tests are disabled by default but get enabled by Travis.

### CODE REVIEW

**Comment by lcamacho** [comment]
This works awesome! I just wonder if It won't be better to use an enviromental variable like FORCE_DB to make quicker run these tests instead of write a new setting on settings/local.py?

**Comment by peterbe** [comment]
FORCE_DB is for a very different purpose.

**Comment by lcamacho** [comment]
Of course but I mean to use an envirionmental variable, like for run selenium tests use RUN_SELENIUM_TESTS=1 ./manage.py test

**Comment by peterbe** [comment]
Ah! Good question. 
Later this year I'm going to remove the settings/local.py thing and replace it entirely with environment variables. 
Don't worry about specifying 10 different environment variables for your local copy every time you run `./manage.py runserver` because there's a way to put all your environment variables in a file. 
That file basically gets parsed very early an and it populates `os.environ`. 

The tool is called python-decouple and it's awesome. I just haven't got around to it yet.

**Comment by lcamacho** [comment]
If it's in the roadmap to change every variable in settings/local.py with environment variables I think we can work with this until then.
Do you know If I merge this is going to update my pr in airmozilla?

**Comment by peterbe** [comment]
Yes it will update your PR against mozilla/master

On Fri, Feb 13, 2015 at 10:50 AM, Leonard Camacho <notifications@github.com>
wrote:

> If it's in the roadmap to change every variable in settings/local.py with
> environment variables I think we can work with this until then.
> Do you know If I merge this is going to update my pr in airmozilla?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lcamacho/airmozilla/pull/1#issuecomment-74305179>.
>



-- 
Peter Bengtsson
Mozilla Web Engineering

**Pull request merged**
